FROM frolvlad/alpine-gcc as builder
RUN apk add libusb-dev
RUN mkdir /src
COPY . /src
WORKDIR /src
RUN make && ls

FROM alpine:3
COPY --from=builder /src/mspdebug /usr/bin/
ENTRYPOINT ['/usr/bin/mspdebug']
CMD ['--help']
